# Ungrouped values, used to make GET-Parameters easier to write
# Values are assigned here only for debugging purposes
mediaPackageId = 'a2ca9b55-5d79-40c7-bfb2-55b2215f4973'

# Debugging values
# Should be deleted in production
[debugging]
ocUrl = 'https://pyca.opencast.org'

[metadata]
show = false

[thumbnail]
show = false